[2025-02-12T20:54:01.343+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T20:54:01.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_omdb_api.teste scheduled__2025-02-12T20:53:00+00:00 [queued]>
[2025-02-12T20:54:01.369+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_omdb_api.teste scheduled__2025-02-12T20:53:00+00:00 [queued]>
[2025-02-12T20:54:01.370+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-12T20:54:01.385+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): teste> on 2025-02-12 20:53:00+00:00
[2025-02-12T20:54:01.391+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1072) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T20:54:01.393+0000] {standard_task_runner.py:63} INFO - Started process 1073 to run task
[2025-02-12T20:54:01.393+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'call_omdb_api', 'teste', 'scheduled__2025-02-12T20:53:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/call_api.py', '--cfg-path', '/tmp/tmptn8l9sye']
[2025-02-12T20:54:01.394+0000] {standard_task_runner.py:91} INFO - Job 163: Subtask teste
[2025-02-12T20:54:01.434+0000] {task_command.py:426} INFO - Running <TaskInstance: call_omdb_api.teste scheduled__2025-02-12T20:53:00+00:00 [running]> on host a7cb053280af
[2025-02-12T20:54:01.507+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Celso Cazetto' AIRFLOW_CTX_DAG_ID='call_omdb_api' AIRFLOW_CTX_TASK_ID='teste' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T20:53:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T20:53:00+00:00'
[2025-02-12T20:54:01.508+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T20:54:01.517+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-12T20:54:01.519+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/pipeline/main.py']
[2025-02-12T20:54:01.527+0000] {subprocess.py:86} INFO - Output:
[2025-02-12T20:54:02.466+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,466 - INFO - ESTOU RODANDO ESSA PORRA
[2025-02-12T20:54:02.467+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,467 - INFO - Carregando o arquivo de configuração
[2025-02-12T20:54:02.468+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,468 - INFO - Buscando os dados de filme do ID:tt0499549
[2025-02-12T20:54:02.592+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,592 - INFO - Dados da API carregados com sucesso
[2025-02-12T20:54:02.593+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,592 - INFO - Iniciando transformação dos dados.
[2025-02-12T20:54:02.600+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,600 - INFO - Estabelecendo conexão com o banco de dados:
[2025-02-12T20:54:02.633+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,633 - INFO - Conexão estabelecida com sucesso.
[2025-02-12T20:54:02.653+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,653 - INFO - Iniciando o inserção na tabela: omdb.filmes
[2025-02-12T20:54:02.657+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,657 - INFO - 0 Inseridos na tabela omdb.filmes
[2025-02-12T20:54:02.661+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,661 - INFO - Iniciando o inserção na tabela: omdb.genero
[2025-02-12T20:54:02.666+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,665 - INFO - 0 Inseridos na tabela omdb.genero
[2025-02-12T20:54:02.675+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,675 - INFO - Iniciando o inserção na tabela: omdb.filme_genero
[2025-02-12T20:54:02.678+0000] {subprocess.py:93} INFO - 2025-02-12 20:54:02,678 - INFO - 0 Inseridos na tabela omdb.filme_genero
[2025-02-12T20:54:02.679+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-02-12T20:54:02.679+0000] {subprocess.py:93} INFO -   File "/opt/***/pipeline/main.py", line 88, in <module>
[2025-02-12T20:54:02.681+0000] {subprocess.py:93} INFO -     conn.insere_filmes(filme_df, 'filmes', genero_df, 'genero', 'filme_genero', 'omdb')
[2025-02-12T20:54:02.681+0000] {subprocess.py:93} INFO -   File "/opt/***/pipeline/connection.py", line 79, in insere_filmes
[2025-02-12T20:54:02.683+0000] {subprocess.py:93} INFO -     self.close()
[2025-02-12T20:54:02.683+0000] {subprocess.py:93} INFO -   File "/opt/***/pipeline/connection.py", line 36, in close
[2025-02-12T20:54:02.684+0000] {subprocess.py:93} INFO -     self.conn.commit()
[2025-02-12T20:54:02.685+0000] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^
[2025-02-12T20:54:02.685+0000] {subprocess.py:93} INFO - AttributeError: 'Connection' object has no attribute 'commit'
[2025-02-12T20:54:02.795+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-12T20:54:02.796+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T20:54:02.805+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-12T20:54:02.808+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=call_omdb_api, task_id=teste, run_id=scheduled__2025-02-12T20:53:00+00:00, execution_date=20250212T205300, start_date=20250212T205401, end_date=20250212T205402
[2025-02-12T20:54:02.821+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 163 for task teste (Bash command failed. The command returned a non-zero exit code 1.; 1073)
[2025-02-12T20:54:02.850+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-12T20:54:02.866+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T20:54:02.869+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
